Repository LostRuins/koboldcpp, pull requests merged in 2023-10, with the labels that each got.

#462 avoid leaving a zombie process for --onready
  koboldcpp.py
Labels: invalid

#466 OpenAI compat API adapter
  koboldcpp.py
Labels: enhancement, completed

#471 Tensor split UI
  .gitignore
  koboldcpp.py
Labels: enhancement
