Repository LostRuins/koboldcpp, pull requests merged in 2024-07, with the labels that each got.

#985 Update kcpp_adapters
  kcpp_adapters/Alpaca.json
  kcpp_adapters/ChatML.json
  kcpp_adapters/Command-R.json
  kcpp_adapters/Gemma-2.json
  kcpp_adapters/Llama-2-Chat.json
  kcpp_adapters/Llama-3.json
  kcpp_adapters/Metharme.json
  kcpp_adapters/Mistral.json
  kcpp_adapters/Phi-3.json
  kcpp_adapters/Vicuna.json
Labels: enhancement, needs review

#982 Add the DRY dynamic N-gram anti-repetition sampler
  common/common.h
  expose.h
  gpttype_adapter.cpp
  koboldcpp.py
Labels: enhancement

#981 Rudimentary support of openai chat completions tools calls
  koboldcpp.py
Labels: enhancement

#1012 New automatic layers
  koboldcpp.py
Labels: enhancement, high priority, needs review

#1031 Fix the penultimate token sometimes being lost with SSE streaming
  koboldcpp.py
Labels: bug, needs review
